dist: trusty

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/codacycoverage clover build/logs/clover.xml
