name: PHP

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
        #, '8.0', '8.1'
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug
        extensions: bcmath

    - uses: actions/checkout@v2

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --no-interaction

    - name: PHPUnit
      run: ./vendor/bin/phpunit --coverage-clover build/clover.xml

    - name: Upload coverage results to Coveralls
      if: matrix.php-versions == '7.1'
      env:
        COVERALLS_RUN_LOCALLY: 1
        COVERALLS_REPO_TOKEN: 4PY3vFXVlLE7HkKNbEDA5JMaeOeIwGhqX
      run: |
        wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar
        chmod +x php-coveralls.phar
        php php-coveralls.phar --coverage_clover=build/clover.xml --json_path=build/coveralls-upload.json -vvv
